### ISSUE TITLE
Handle vessels selection

### ISSUE THREAD

**Issue by tanega** [tanega/trailwatch-front-kickoff#12]
## Todos

- [ ] Add combox to fuzzy search vessels
- [ ] Add vessels to a selection
- [ ] Change position color accordingly on the map
