### ISSUE TITLE
Vessel position layer 

### ISSUE THREAD

**Issue by tanega** [tanega/trailwatch-front-kickoff#8]
## Todos

- [ ] Add GeoJsonLayer with last know positions
- [ ] Configure layer style with custom markers
- [ ] Handle active vessel (with popup preview) 
- [ ] Handle vessels selection
